apiVersion: v1
kind: Service
metadata:
  name: http-honeypot-svc
  namespace: sigilhive
  labels:
    app: http-honeypot
spec:
  type: LoadBalancer
  selector:
    app: http-honeypot
  ports:
    - name: https
      port: 8443
      targetPort: 8443
      protocol: TCP
